### ISSUE TITLE
章节底部无法点击翻页

### ISSUE THREAD

**Issue by mix-future** [tgxhx/vue-reader#4]
章节快要到底的时候，没办法直接点击滚动到底部。
另外有没有可能做一个左右翻页的功能呢，就像百度阅读、潇湘书院那样的？好像网页上很难确定每个字符所占的空间，从而判断每页显示的字数。但是常用的文本字符也就那么多，中文占的空间还是固定的，个人感觉应该可以逐个计算出来吧

**Comment by tgxhx** [comment]
左右分页当时考虑做过，做这个应该可以，但是考虑到应该会很麻烦，屏幕尺寸、分辨率、字体、行高、间距等等，所以这个没有做，以后看有没有时间会考虑试试。
