### ISSUE TITLE
按要求创建了显示跨域问题

### ISSUE THREAD

**Issue by HJunYi** [tgxhx/vue-reader#6]
您好，我按照你的要求配置了环境但是出现错误，然后把前端的src/assets/js/utils下的api改为了‘http://127.0.0.1:3333’然后又出现新问题 提示跨域问题，请问这该如何解决呢？谢谢

**Comment by tgxhx** [comment]
在你用的那个node-api项目的app.js中把跨域的一段注释取消

**Comment by HJunYi** [comment]
好像还是不行，又遇到其他错误了，还是加载不到数据，您能加我qq 给我点指导吗？我刚接触这个不太会，谢谢了，qq:1210778146

**Comment by HJunYi** [comment]
可以运行了，非常感谢
